apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # 아래 이미지는 GitHub Actions가 sed 명령어로 자동 교체합니다.
          image: 215572961831.dkr.ecr.ap-northeast-2.amazonaws.com/solog-frontend:a462d02182cf76c8f3035aa5077ede69a870ad43
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          # 헬스 체크 (Nginx가 잘 떠있는지 확인)
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5