apiVersion: apps/v1
kind: Deployment
metadata:
  name: solog-backend
  namespace: default
  labels:
    app: solog-backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: solog-backend
  template:
    metadata:
      labels:
        app: solog-backend
    spec:
      containers:
        - name: solog-backend
          image: 215572961831.dkr.ecr.ap-northeast-2.amazonaws.com/solog-backend:f0ad62e73d5d614f117d71f4f582ed03d06f8a65
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_API_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: OPENAI_API_URL
            - name: GRAFANA_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GRAFANA_URL
            - name: GRAFANA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GRAFANA_TOKEN

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"