apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: solog-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: solog-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # CPU 사용률이 60%를 넘으면 확장 시작