apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/backend

images:
- name: solog-backend
  newName: 215572961831.dkr.ecr.ap-northeast-2.amazonaws.com/solog-backend
  newTag: bb906343c6f11397e4ea3dfa8c804ddf598c30a4
