apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/backend

images:
- name: solog-backend
  newName: sologregistry000807.azurecr.io/solog-backend
  newTag: 3d2e1b138ab46e58d20dd212ecfa8a4f548c2df9
