apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/frontend

patches:
- path: ingress-patch.yaml

images:
- name: solog-frontend
  newName: 215572961831.dkr.ecr.ap-northeast-2.amazonaws.com/solog-frontend
  newTag: 223dffb44909d3e58690d15a5dd3ed3b20908129
