apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/frontend

patches:
- path: ingress-patch.yaml

images:
- name: solog-frontend
  newName: sologregistry000807.azurecr.io/solog-frontend
  newTag: 763525fd09ac2e18ef106ff712138952fde6f2a1
