apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/frontend

patches:
- path: ingress-patch.yaml

images:
- name: solog-frontend
  newName: sologregistry000807.azurecr.io/solog-frontend
  newTag: 0feeb6bc2d7b2afbbe3fcfd43416f82cd1247106
